Make AssessmentViewModel open to be able to override BranchNodeStateI…
Sage-Bionetworks/AssessmentModel-KotlinNative pull request #49
Opened 2020-09-01 20:05 UTC by elkasvirElka

…mpl field

2020-09-01 21:43 UTC, nategbrown9 commented on presentation/src/main/java/org/sagebionetworks/assessmentmodel/presentation/AssessmentFragment.kt
> +            .get(AssessmentViewModel::class.java)
Do you want this pulled out into a helper method you can override?  Then you have less duplicate code than overriding initAssessmentViewModel().

2020-09-02 20:16 UTC, nategbrown9 requested changes
Looks good. Just need to remove an import.

2020-09-02 20:16 UTC, nategbrown9 commented on presentation/src/main/java/org/sagebionetworks/assessmentmodel/presentation/AssessmentViewModel.kt
> +import org.sagebionetworks.assessmentmodel.presentation.mtbAssesssmentTest.MtbAssessmentViewModel
This import shouldn't be here.

2020-09-02 20:36 UTC, elkasvirElka commented on presentation/src/main/java/org/sagebionetworks/assessmentmodel/presentation/AssessmentViewModel.kt
> +import org.sagebionetworks.assessmentmodel.presentation.mtbAssesssmentTest.MtbAssessmentViewModel
deleted.

2020-09-02 21:17 UTC, nategbrown9 approved these changes

2020-09-02 21:18 UTC, merged