Assessment hierarchy
Sage-Bionetworks/AssessmentModel-KotlinNative pull request #61
Opened 2021-01-22 19:34 UTC by nategbrown9

Add support for loading an assessment containing other assessments.

2021-01-25 20:28 UTC, syoung-smallwisdom requested changes
A few tweeks to suggest.

2021-01-25 20:28 UTC, syoung-smallwisdom commented on assessmentModel/src/commonMain/kotlin/serialization/Serialization.kt
> +
I would suggest the following:

First, refactor `Assessment` to pull out the bits which come from the server.

```
interface AssessmentInfo {

    /**
     * The identifier for the assessment.
     */
    val identifier: String

    /**
     * The [versionString] may be a semantic version, timestamp, or sequential revision integer.
     */
    val versionString: String?

    /**
     * The [schemaIdentifier] is used to allow a group of [Assessment] models to all map to the same
     * table in a data base.
     */
    val schemaIdentifier: String?
}
```

Which makes the Assessment look like this:
```
interface Assessment : BranchNode, ContentNode, AssessmentInfo
``` 

Then change the `ModuleInfoProvider` to be:
```
/**
 * The [ModuleInfoProvider] provides methods to lookup the necessary [ResourceInfo] and [Json] to
 * load an [Assessment] using the provide the platform specific [FileLoader].
 */
interface ModuleInfoProvider {

    val fileLoader: FileLoader

    fun getRegisteredResourceInfo(assessmentInfo: AssessmentInfo): ResourceInfo? = null

    fun getRegisteredJsonDecoder(assessmentInfo: AssessmentInfo): Json? = null

    /**
     * Allows the provider to return an [Assessment] (for the given [assessmentInfo]) that is not
     * encoded as a JSON serialized object.
     */
    fun getRegisteredAssessment(assessmentInfo: AssessmentInfo): Assessment? = null
}
```

And finally:
```
/**
 * A [TransformableAssessment] is a placeholder that can be used to contain just enough information about an
 * [Assessment] to allow referencing the resource information needed to load the actual [Assessment] on demand. This
 * allows using a "placeholder" that can be vended from a different source from the actual assessment. For example,
 * an active task may be defined using a hardcoded JSON file and included in a module but requested via a
 * [TransformableAssessment] that is vended from a server.
 */
interface TransformableAssessment : Assessment, TransformableNode {
    override fun unpack(moduleInfoProvider: ModuleInfoProvider, resourceInfo: ResourceInfo, jsonCoder: Json): Assessment {
        val assessment = moduleInfoProvider.getRegisteredAssessment(this)
        return if (assessment != null) assessment else {
            val curResourceInfo = moduleInfoProvider.getRegisteredResourceInfo(this) ?: resourceInfo
            val serializer = PolymorphicSerializer(Assessment::class)
            val jsonString = moduleInfoProvider.fileLoader.loadFile(this, resourceInfo)
            val curJsonCoder = moduleInfoProvider.getRegisteredJsonDecoder(this) ?: jsonCoder
            val unpackedNode = curJsonCoder.decodeFromString(serializer, jsonString)
            unpackedNode.unpack(moduleInfoProvider.fileLoader, curResourceInfo, curJsonCoder)
        }
    }

    override fun getNavigator(): Navigator = throw IllegalStateException("Attempted to get a navigator without first unpacking the Assessment.")
}
```

2021-01-25 20:28 UTC, syoung-smallwisdom commented on assessmentModel/src/commonMain/kotlin/serialization/FileAssessmentProvider.kt
> +        return unpackedNode.unpack(moduleInfoProvider, curResourceInfo, curJsonCoder)
val unpackedNode = **_curJsonCoder._**decodeFromString(serializer, jsonString)

2021-01-26 01:49 UTC, syoung-smallwisdom approved these changes
Some nits and a PR with suggested changes.

2021-01-28 22:53 UTC, nategbrown9 commented on assessmentModel/src/commonMain/kotlin/navigation/NodeState.kt
> +            customBranchNodeStateProvider?.customNodeStateFor(it, this) ?: BranchNodeStateImpl(it, this)
I think for developers that don't need a custom `BranchNodeState` implementation, it is easier to keep them separate. I changed the method name on the `BranchNodeState` interface to `customLeafNodeStateFor(node: Node, parent: BranchNodeState)' to be more explicit.

2021-01-28 23:25 UTC, syoung-smallwisdom approved these changes
A little cleanup and a question.

Otherwise, looks good.

2021-01-28 23:25 UTC, syoung-smallwisdom commented on assessmentModel/src/commonMain/kotlin/ModuleInfo.kt
> +        return sublist.first().unpack(assessmentPlaceholder,this, registryProvider)
```suggestion
        return sublist.first().unpack(assessmentPlaceholder, this, registryProvider)
```
Oops.

2021-01-28 23:25 UTC, syoung-smallwisdom commented on assessmentModel/src/commonMain/kotlin/navigation/NodeState.kt
> +            customBranchNodeStateProvider?.customNodeStateFor(it, this) ?: BranchNodeStateImpl(it, this)
I guess I'm confused as to why an assessment developer may want to use a custom BranchNodeState but *not* want to use that same pattern for the leaf node states. Especially given that you are separating the concerns of "handle finished" and "present UI". Why wouldn't the custom leaf state *also* be vended by the same provider (if it isn't handled by the branch node state using override)?

I'm wondering if maybe the same kind of pair-programming day with Ella would be a good idea?

2021-01-28 23:25 UTC, syoung-smallwisdom commented on assessmentModel/src/commonMain/kotlin/serialization/Nodes.kt
> + * TODO: syoung 01/27/2021 Add unit test of the serialization.
```suggestion
```

This is done. Forgot to remove the TODO comment.

2021-01-29 00:16 UTC, nategbrown9 commented on assessmentModel/src/commonMain/kotlin/navigation/NodeState.kt
> +            customBranchNodeStateProvider?.customNodeStateFor(it, this) ?: BranchNodeStateImpl(it, this)
I took a look at the MobileToolBox code, and they are reverse of what I would have argued would be the common case. They have a custom `BranchNodeState` implementation, but no custom leaf NodeStates.

2021-01-29 04:20 UTC, merged